import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";

import { Mulish } from 'next/font/google'
import Footer from "./components/Footer";
// import Footer from "./components/Footer";
 
const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie Flix - a movies review platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body  >
          <Header/>
        {children}
 <Footer/>
        </body>
    </html>
  );
}
